import React, { useEffect } from "react";
import "./PrivacyPolicy.scss";

const PrivacyPolicy = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
    document.title = "Privacy Policy | F1-Telemetry";
  }, []);

  return (
    <div className="privacy-policy-container font-lato text-white grow">
      <div className="max-w-[1000px] mx-auto px-24 pt-4 md:pt-8 pb-32 md:pb-64">
        <h1 className="heading-2 mb-32 gradient-text-light uppercase tracking-xs">
          Privacy Policy
        </h1>
        <p className="text-neutral-400 mb-48">Last Updated: April 13, 2026</p>

        <section className="mb-48">
          <h2 className="text-2xl font-bold mb-16 uppercase tracking-xs">
            1. Introduction
          </h2>
          <p className="text-neutral-300 leading-relaxed">
            Welcome to F1-Telemetry. We value your privacy and are committed to
            protecting your personal data. This Privacy Policy explains how we
            collect, use, and safeguard your information when you visit our
            website.
          </p>
        </section>

        <section className="mb-48">
          <h2 className="text-2xl font-bold mb-16 uppercase tracking-xs">
            2. Data We Collect
          </h2>
          <h3 className="text-xl font-semibold mb-8 text-neutral-200">
            2.1 Google Analytics
          </h3>
          <p className="text-neutral-300 leading-relaxed mb-16">
            We use Google Analytics, a web analytics service provided by Google,
            Inc. ("Google"), to understand how users interact with our website.
            Google Analytics uses "cookies"—which are text files placed on your
            computer—to collect standard internet log information and visitor
            behavior information in an anonymous form.
          </p>
          <p className="text-neutral-300 leading-relaxed">
            The information generated by the cookie about your use of the
            website (including your IP address, anonymized by Google Analytics)
            is transmitted to Google. This information is then used to evaluate
            visitors' use of the website and to compile statistical reports on
            website activity for F1-Telemetry.
          </p>
        </section>

        <section className="mb-48">
          <h2 className="text-2xl font-bold mb-16 uppercase tracking-xs">
            3. Cookie Consent
          </h2>
          <p className="text-neutral-300 leading-relaxed mb-16">
            In compliance with privacy regulations (such as GDPR and the
            ePrivacy Directive), we require your explicit consent before loading
            any non-essential tracking cookies, including those used by Google
            Analytics.
          </p>
          <p className="text-neutral-300 leading-relaxed">
            When you first visit our site, you are presented with a cookie
            banner. If you choose "Accept", we will store your preference in
            your browser's local storage and initialize Google Analytics. If you
            choose "Reject", no tracking scripts will be loaded. You can change
            your preference at any time by clearing your browser's local storage
            and refreshing the page.
          </p>
        </section>

        <section className="mb-48">
          <h2 className="text-2xl font-bold mb-16 uppercase tracking-xs">
            4. How We Use Data
          </h2>
          <p className="text-neutral-300 leading-relaxed">
            We use the data collected through Google Analytics solely to:
          </p>
          <ul className="list-disc list-inside text-neutral-300 mt-8 space-y-4">
            <li>Analyze site traffic and user engagement patterns.</li>
            <li>Identify technical issues and optimize website performance.</li>
            <li>Improve our content and overall user experience.</li>
          </ul>
        </section>

        <section className="mb-48">
          <h2 className="text-2xl font-bold mb-16 uppercase tracking-xs">
            5. Your Rights
          </h2>
          <p className="text-neutral-300 leading-relaxed">
            Under certain data protection laws, you have rights in relation to
            your personal data, including the right to request access,
            correction, erasure, or restriction of processing. Since we do not
            collect personal data like names or email addresses directly, most
            of the data we hold is anonymous and aggregated through Google
            Analytics.
          </p>
        </section>

        <section className="mb-48">
          <h2 className="text-2xl font-bold mb-16 uppercase tracking-xs">
            6. Contact Us
          </h2>
          <p className="text-neutral-300 leading-relaxed">
            If you have any questions about this Privacy Policy or our treatment
            of your data, please reach out to us via our Instagram page or
            through the contact channels listed on our main site.
          </p>
        </section>

        <div className="divider-glow-dark my-48" />

        <p className="text-neutral-500 text-sm italic">
          Disclaimer: This website is a fan-made project and is not associated
          in any way with the Formula 1 companies.
        </p>
      </div>
    </div>
  );
};

export { PrivacyPolicy };
