export const locationMaps = {
    melbourne: "albert_park",
    austin: "americas",
    bahrain: "bahrain",
    sakhir: "bahrain",
    baku: "baku",
    budapest: "hungaroring",
    imola: "imola",
    "são paulo": "interlagos",
    jeddah: "jeddah",
    "marina bay": "marina_bay",
    monaco: "monaco",
    spielberg: "red_bull_ring",
    "mexico city": "rodriguez",
    shanghai: "shanghai",
    silverstone: "silverstone",
    "spa-francorchamps": "spa",
    suzuka: "suzuka",
    "las vegas": "vegas",
    montréal: "villeneuve",
    zandvoort: "zandvoort",
    miami: "miami",
    monza: "monza",
    barcelona: "catalunya",
    lusail: "losail",
    "yas island": "yas_marina",
    australia: "albert_park",
    austria: "red_bull_ring",
};
